## OUTER 조인을 이용해서 입양을 가지못한 동물 검색
## 입양들어온 순으로 정렬
## 가장 높은 세마리 출력

SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS as INS
LEFT OUTER JOIN ANIMAL_OUTS as OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID IS NULL
ORDER BY INS.DATETIME
LIMIT 3